### ISSUE TITLE
Revisit : Handler interface generated per template

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1034]
@mandarjog proposed that we might want to rethink on how the Builder and Handler interfaces will be used by mixer framework to interact with Adapters.

With the current design, if there is any change in the Instance, we require creation of the handler completely. which would mean connection needs to be established again.

Proposals:
- Invoked getBuilderInfo(adapterConfig) first, let the adapter establish connection. Then call configureXXXX on it and at the end call Build. This approach potentially can allow skip connection establishing step in scenarios where there is just change in inferred types. @mandarjog I am assigning this to you for now to explain the concern, we can discuss this in tomorrow's Mixer standup. I can take this bug after our discussion.

NOTE: this does not block the implementation going on right now..

**Comment by geeknoid** [comment]
The current split is necessary in order to enable adapters that require config-time setup to work properly. Adapters that don't need this don't need to do anything special. Adapters for which connection establishment is a big deal can manage these connections themselves at the level of the builder. They can share/reuse connections as necessary.

I think the only thing we need to do is introduce a Close method on the builder such that we can allow adapters to clean up after themselves.

**Comment by geeknoid** [comment]
Sunny and I just had an additional conversation on this front. We decided the right approach here is to leave things the way they are.

If an adapter finds it problematic to teardown & reestablish connections when handlers are created and deleted, then the adapter can itself implement a global connection cache that it manages internally. We don't need to be involved in that process at all.

We probably should invest in creating a more complex adapter that works on this plan to show how it is done. Basically though, it involves the adapter maintaining a cache of <connection parameters, connection object>.
