### ISSUE TITLE
aspect List checkExpression does not take source.ip

### ISSUE THREAD

**Issue by mvle** [istio/mixer#1063]
checkExpression should take a string, but when tested with source.ip attribute, get an error:

rules:
- aspects:
  - kind: lists
    adapter: ipList
    params:
      blacklist: true
      checkExpression: source.ip

I get the following error:
Error: failed rule creation with status 400: 2 errors occurred:
* serviceConfig: failed validation
* /:lists[0]: failed to parse params: 1 error occurred:
* lists: aspect validation failed: 1 error occurred:
* checkExpression: error type checking expression: expression 'source.ip' evaluated to type IP_ADDRESS, expected type STRING

**Comment by ZackButcher** [comment]
The issue here is that the type of the IP List Checker input is `ValueType.STRING`, [which is checked here](https://github.com/istio/mixer/blob/master/pkg/aspect/listsManager.go#L78). The easiest fix would be to update that code to check for [any of these ValueTypes](https://github.com/istio/api/blob/98f8bfa16202f54afaa4d89d50a95e995fc2eb0c/mixer/v1/config/descriptor/value_type.proto#L43-L52) in addition to `STRING`.

A secondary, larger-in-scope fix would be to update how we handle those String-ish Attributes to coerce them into String. I'm not a huge fan of this: we should do it at runtime during evaluation, but not during type checking up front.

IMO the correct fix is in the listsManager code I linked above.

**Comment by geeknoid** [comment]
Open #1085 to track this feature request in the context of the new Mixer adapter model.
