### ISSUE TITLE
Review API spec

### ISSUE THREAD

**Issue by louiscryan** [istio/mixer#22]
@smawson @geeknoid 

Tracking issue for discussion of the API specification in 

https://github.com/istio/mixer/tree/master/api/v1

**Comment by smawson** [comment]
Here is my strawman:

check.proto: Do we need a separate "operation_id" or something to indicate which operation is being called, or do we assume that will be passed as a fact?


report.proto:

Drop aggregation, drop log/metric specifics, have mixer derive those from the facts. If we need to optimize with aggregation we can add a new api later:

message ReportRequest {
  int64 request_id = 1;
  map<string, string> facts = 2;
}

message ReportResponse {
  int64 request_id = 1;
  google.rpc.Status result = 2;
}


quota.proto:

Not as sure what to do here, seems a bit complex, but I'm not sure how to simplify. What is absolutely required to send along, and what could instead be calculated by mixer?

I think we could maybe at least get rid of dedupe_id, and require that request_id+quota_name be effectively a uuid.

Also the QuotaDescriptor thing seems to assume some particular configuration model, and it would be best if we can avoid that leaking into the api.

So what are the abstract pieces of information, beyond a set of facts, that Mixer needs to handle a quota call?

We can work from that towards an API.

**Comment by smawson** [comment]
@douglas-reid @mandarjog

**Comment by douglas-reid** [comment]
@smawson in your minimal ReportRequest, is a 'fact' something like:

'jsonPayload':'{"env":"dev", "build":"service-20161202v3",...}' 

Would we be worried about sacrificing some level of semantics (log entries are oneof, etc.)?  Does that make it harder for callers to understand what 'facts' will be processed?

It seems that this approach will co-mingle request metadata with request data.  Is that the intent?

Perhaps an aside: does the term 'fact' bother anyone else? I realize that 'context_params' is probably too verbose, but 'fact', to me, implies something beyond what is being passed. There is no required connection to some sort of ground truth for these key-value pairs, correct?

**Comment by geeknoid** [comment]
Sven,

The API is designed to be called by both the proxy and the service. The proxy is responsible for supplying the parameters to the report calls, while the facts determine the 'address' of the data.

request_id is only scoped to the current stream, there is no globally unique guarantee/requirement, which is a boon to the caller as the request id can be handled completely in the client library with a simple in-memory counter. dedup_id is different and needs to be globally unique. This is why it is different.

**Comment by louiscryan** [comment]
1. If we want to issue a check & report with the same set of facts we have to send all the facts twice. It seems more efficient to have an outer object carry facts and then have a list of event types nested within it.

2. We should canonicalize common facts into the schema. Using a generic name/value map makes the protocol expensive for the most common names and eliminates the possibility of have these well-known names having inline documentation. Canonicalizing them would also give us the opportunity to have them be strongly typed. We could also decorate the schema with annotations to facilitate the rule processing engine. Consider creating a facts.proto?

3. LogEntry is an interesting schema given that much of the log detail probably overlaps with information reported in the facts. Not entirely sure what to do about it however, maybe payload could specify a templating rule for the mixer to execute? How does LogEntry.labels relate to the facts in ReportRequest?

4. Don't we need Check to return an 'effective amount' for local quota caching

5.  Many of the systems we'll be working with are already generating UUIDs for call-graph roots. For example Envoy generates a UUID (36 bytes) to facilitate dapper style tracing with zipkin/lightstep etc. Is this notion of root-event one that we want to track? Maybe we just treat it as a fact for the moment.

https://lyft.github.io/envoy/docs/configuration/http_conn_man/headers.html#config-http-conn-man-headers-x-request-id
http://zipkin.io/pages/data_model.html


Misc...
- Rename request_id to id and document that its not a GUID, is local to a specific context such as the RPC channel
- QuotaRequest.descriptor_name name seems like it could be more immediate, 'quota_name' ?
- QuotaRequest.amount if it's always >= 0 use unsigned? (minor)
- QuotaRequest.dedepulication_id - Strings are expensive, use bytes for UUIDs?
- QuotaResponse.result.effective_amount - Can be negative? If so doc
- ReportRequest.monitored_resource_descriptor_name - A bit opaque, make more immediate?
- LogEntry.log_name - Why is the source specifying the log target, isn't that the mixers job? What will the mixer do with this

**Comment by douglas-reid** [comment]
RE: LogEntry schema and facts

If we continue to allow multiple LogEntries per report, I'm not convinced that we can avoid having some level of schema. For instance, timestamps (and/or severity) of individual entries may differ. That logging metadata is arguably not part of the log entries themselves. We could probably require that all LogEntries in a single request be part of the same log_collection, however.

**Comment by mandarjog** [comment]
+1 for defining a Facts vocabulary in protobufs as fields or enums.
We will however need to support extensible key-value-type facts so proxies and other fact providers  can easily inject new facts.

re Logs: 
What is the exact use case for logs?
In the existing service control client, there is great overlap between logs and metrics.
And if everything can be inferred at mixer that would be even better.

**Comment by mandarjog** [comment]
If Logs are not needed for the proxy usecase, we should just drop 
```
repeated LogEntry
repeated MetricValue
```
from ReportRequest proto and have all that assembled at the mixer.

We will revisit it if the direct calling from Service usecase becomes strong.

a metric definition in istio config like
```
- name: request_size_by_status_...
       elementary_measurement: request.size 
       metric_kind: DELTA
       value_type: INT64
       labels:
      - key: consumer_id
      - key: status_code
      - key: service_id

- name: request_size_by_status_code
       elementary_measurement: request.size 
       metric_kind: DELTA
       value_type: INT64
       labels:
      - key: status_code
```
Should tell the proxy that it needs to send [request.size, consumer_id, status_code, service_id] facts. Mixer will assemble it in a metric.

**Comment by douglas-reid** [comment]
@mandarjog Agreed. This notion will keep it simple and focused on the proxy-mixer case. To my understanding, this means:

1. Push off arbitrary log stream support for services to later (eliminate LogEntry from report.proto).
1. Add facts.proto with schema for "well-known" proxy-relevant facts.

**Comment by wora** [comment]
A couple of general comments first.

1. I recommend we rename `facts` to `attributes`. Attribute is a widely used term for similar concepts in computer science. People will have the almost correct perception even without reading any documentation. Facts needs to be explained for every single person, and it doesn't seem to have real advantage. In reality, many facts are computed values (by various components or systems).

2. Based on our experience with Service Control API, I think we need to handle some necessary complexity.

2.1 The CheckResponse should include `unused_facts`. This informs clients not to send useless facts in the future. It will greatly reduce runtime cost and improve caching efficiency. Otherwise, the practical cache hit rate will be close to 0.

2.2 How would client know how long the check response can be cached? Is it defined by the service config?

3. Let's not define enum or field for any business logic. Use documentation for that. So different implementation can define their own business logics. This will be a platform API, so any concept that can't last at least 5 years should not be visible on the API surface (documentation is fine).

4. On report side, which component is responsible for cache and aggregation? If we want to support memcache like services, where each server can handle millions of request per second, the proxy must be able to aggregate. For low level services, such as network load balancer, reporting every second is probably enough. For high level services, such as API servers, report every 5-15s is sufficient. AWS monitoring system has 60s aggregation window.

5. Can we define 3 interfaces with one method each? It doesn't add any runtime overhead, but it makes API design more flexible. The 3 features have almost no overlapping except the common definition of facts.

6. Since there is no "resource" in the API design, there is no way to dispatch API calls. One mixer must be able to handle all API requests. This design works fine when you run a mixer in a small cluster. It won't work if someone want to run the mixer as a service, as we can do any type of sharding. This is one of reason why all Google APIs are resource oriented.

6.1 If we want to be compatible with Service Broker, every API call must address a "service instance" explicitly. The currently design is pure RPC oriented design and everything is hidden inside facts.

Lastly, let's keep the API design close to our style guide, which I will publish soon. It will help to keep gRPC APIs consistent down the road.

**Comment by douglas-reid** [comment]
There was a face-to-face discussion of the current API design. The outcomes from the meeting, to my recollection:

- Support for application logging is desired, but more research is needed for determining the shape of the API. **Action**: open issue for `Logs API`, with current `LogEntries` proposal PR.
- Schema for well-known `facts` is desirable. There should be some minimal typing (to support amounts, etc.) and examples of how it could be extended.
- When considering the proposal for a separation between `facts` and `labels` (derived from `facts`), there was a preference for just having one concept (only `facts`).

If others had different or better recollections, please add them.

**Comment by smawson** [comment]
Hong awesome feedback, some thoughts.

1. I don't have a strong opinion on facts vs. attributes, the only thing I like about facts is you can say "I'm Reporting on the Facts".  Vs. "I'm reporting some Attributes".  Doesn't seem as strong :)  But generally I'd be totally fine if we called these attributes.

2.1: We plan on having the proxy know exactly what facts are needed for any particular method call ahead of time. So unused_facts isn't needed, we'll only ever send needed facts.

2.2: Cache timeout TBD, we need to figure that out. Prefer to not muddy the API if we can, maybe belongs in config?

3: The 5 year concept idea is a good one. We're leaning towards defining some well-known set of facts, but we'll use the 5 year idea for any of those. For example "payload.size" is probably something that would survive 5 years, or "source.ip". Originally I liked only using docs but the others here convinced me that defining a well known set in a proto is worth it for both efficiency and for ensuring consistent usage.

4: Both the Proxy and the Mixer will aggregate, over the longer term.  I'm hoping we can define a generic aggregation mechanism for facts, rather than only supporting aggregation for pre-defined types like metrics. That way aggregation is a broad feature and could be widely used. TBD what that would look like though, but I do have thoughts.

5: I think we either go the 3 interfaces route (CheckService.Check, ReportService.Report) or we go the route Louis suggested of a single method.  The single method would let us share facts across multiple calls, but I'm not sure it is warranted yet.  Maybe we start with 3 interfaces and if we need a meta one later we can add it? I'm a little worried about us over-optimizing, our initial use cases will NOT be high performance, and we can always add a v2 API as needed.

6: We haven't given a lot of thought to a fully multi-tenant mixer api, that's something we should spend more time on. We don't really know what the resource we're talking about is, so yeah we should probably figure that out.  We have the same problem in the config space, we want to attach each config to a resource. So maybe once we solve it there we can import that into the API. @mandarjog does that make sense?

6.1: Service Broker compat is a non-goal, we explicitly want to operate without requiring service broker concepts.

7: Style guide: Happy to see what changes would be suggested by style guide once we get an overall structure we like :)

**Comment by wora** [comment]
Sounds like we have pretty good consensus.

2.1 Some API key has IP address restriction, some doesn't. If we include IP address for Check, there is little chance for aggregation. How do we handle similar issues?

6. If we depend on service config, then service name will be the primary resource and we will dispatch on it. If we use Service Broker model, then service instance will be the primary resource. Without a primary resource, we can't use the API for multi-tenant setup (at least not effectively).

7. Let's make incremental adjustment as needed. I don't see we have much gap.

**Comment by geeknoid** [comment]
Louis, here's some feedback on your comments.

Rename request_id to id and document that its not a GUID, is local to a specific context such as the RPC channel
	Why the less descriptive name? I like the fact it's the same name in the request and in the response. A naked
	"id" has no semantic meaning.

QuotaRequest.descriptor_name name seems like it could be more immediate, 'quota_name' ?
	Just 'name' implies it's the name of the request. It's not, it's the name of the schema that
	describes the metadata for the request.

QuotaRequest.amount if it's always >= 0 use unsigned? (minor)
	Can be negative, that's how you free quotsa.

QuotaRequest.dedepulication_id - Strings are expensive, use bytes for UUIDs?
	Will do.

QuotaResponse.result.effective_amount - Can be negative? If so doc
	Can't be negative. I'll clarify the docs

ReportRequest.monitored_resource_descriptor_name - A bit opaque, make more immediate?
	I'll see about a shorter name, but in general I prefer descriptive rather than cryptic names.

LogEntry.log_name - Why is the source specifying the log target, isn't that the mixers job? What will the mixer do with this
	Following the review, we'll take this underground for now.

**Comment by geeknoid** [comment]
Hong, this is feedback on your first batch of comments:

1. Renaming facts to attributes.
	OK.

2.1 Including 'unused_facts' in CheckResponse.
This was in there originally, but Sven thought we could do this through config rather than dynamically. I decided to take out the field for now until the implementation work shows that we need it.

2.2 Cacheability TTL of the data obtained from the mixer should be made explicit in the  return data. This will make it simpler for clients to deal.

3. I disagree with the idea that strings are better than enums in API definitions. Strings merely obfuscate the API surface and make the protocol less efficient. In the end, you still need some code in the implementation that deals with all enum values or all string values.

4. We expect the proxy to do aggregation. The problem is that most backends we will interact with do not
support aggregated data. So we need to be flexible here somehow. Ideally, we would aggregate in a non-lossy way in the proxy and then deaggregate in the mixer for those backends that don't support aggregated data.

5. What is the value of defining three distinct interfaces? It does add complexity in the conceptual model, it would require different gRPC endpoints (I think), etc.

6. The point about resources is interesting. I need to think about it.

**Comment by geeknoid** [comment]
Hong, this feedback to your second batch of comments:

_2.1 Some API key has IP address restriction, some doesn't. If we include IP address for Check, there is little chance for aggregation. How do we handle similar issues?_

That's a very good point. I'll leave unused_facts out of the API for now until it's time to implement this stuff. At that point, it's likely we'll find there's no other way to get this working efficiently end-to

_ If we depend on service config, then service name will be the primary resource and we will dispatch on it. If we use Service Broker model, then service instance will be the primary resource. Without a primary resource, we can't use the API for multi-tenant setup (at least not effectively)._

This just boils down to supporting dispatching from the proxy to the mixer based on some sort of "fact shard". I don't believe we need to bring in any notion of instances/service broker/service name as a first class concept.

**Comment by louiscryan** [comment]
On Tue, Dec 6, 2016 at 10:48 AM, Martin Taillefer <notifications@github.com>
wrote:

> Louis, here's some feedback on your comments.
>
> Rename request_id to id and document that its not a GUID, is local to a
> specific context such as the RPC channel
> Why the less descriptive name? I like the fact it's the same name in the
> request and in the response. A naked
> "id" has no semantic meaning.
>
Fair enough

> QuotaRequest.descriptor_name name seems like it could be more immediate,
> 'quota_name' ?
> Just 'name' implies it's the name of the request. It's not, it's the name
> of the schema that
> describes the metadata for the request.
>
'descriptor' feel like an odd name for a quote 'rule' to be enforced. How
much do we want the client to know/control which quotas are to be enforced?
This seems like an odd separation of concerns

Wouldn't it be better for the client to say that it's consuming resources
by some amounts and for the mixer to decide which of those to quota on? If
the client needed to return quota the mixer could tell it which quotas it
consumed from on the initial check?


> QuotaRequest.amount if it's always >= 0 use unsigned? (minor)
> Can be negative, that's how you free quotsa.
>
Comment says  "/ The amount by which to change the quota value's cell (must
be >= 0)"

**Comment by geeknoid** [comment]
You're right about the amount needing to be >= 0, I got confused with a
previous design iteration. I'll change the type to be unsigned.

Now regarding the quota stuff, I think we're not lined up on how I envision
things fitting together. The model I designed wotked consistently for
logging, metrics, quotas, permissions, etc. It goes like this:

The caller specifies in code the parameters for an operation:

Log: Type (i.e. descriptor) of log entry to generate and payload for the
entry
Metric: Type (i.e. descriptor) of metric to generate, and the actual metric
value
Quota: Type (i.e. descriptor) of quota to update, and the amount of quota
delta to apply.


The LogDescriptor, MetricDescriptor, QuotaDescriptor messages provide the
fact metadata for the individual operations:

   - Log: Each log entry descriptor defines the set of facts that should be
   collected for any log entry of that type.


   - Metric: Each metric descriptor defines the set of facts that are used
   to address any single metric value. This basically determines the set of
   dimensions of the metric value.


   - Quota: Like metric descriptors, quota descriptors end up listing the
   set of facts used for each quota of the given type, which determines the
   dimensions of the underlying value.


The mixer takes the input from the caller, looks up the associated
descriptors to know the require set of facts. The mixer then composes
together a struct that contains the parameters from the caller along with
the resolved facts and hands this to the adapters.

So there's a clean separation between what the code knows and what the
config specifies. Only the code knows which metric value to update, which
quota value to update at a given point in time. This is not something that
makes sense to control through config. Config is used by the operator to
determine the dimensions against which the metric and quota are measured,
which is precisely the kind of control they need.

**Comment by louiscryan** [comment]
On Tue, Dec 6, 2016 at 11:09 AM, Martin Taillefer <notifications@github.com>
wrote:

> You're right about the amount needing to be >= 0, I got confused with a
> previous design iteration. I'll change the type to be unsigned.
>
> Now regarding the quota stuff, I think we're not lined up on how I envision
> things fitting together. The model I designed wotked consistently for
> logging, metrics, quotas, permissions, etc. It goes like this:
>
> The caller specifies in code the parameters for an operation:
>
> Log: Type (i.e. descriptor) of log entry to generate and payload for the
> entry
> Metric: Type (i.e. descriptor) of metric to generate, and the actual metric
> value
> Quota: Type (i.e. descriptor) of quota to update, and the amount of quota
> delta to apply.
>
>
> The LogDescriptor, MetricDescriptor, QuotaDescriptor messages provide the
> fact metadata for the individual operations:
>
> - Log: Each log entry descriptor defines the set of facts that should be
> collected for any log entry of that type.
>
>
> - Metric: Each metric descriptor defines the set of facts that are used
> to address any single metric value. This basically determines the set of
> dimensions of the metric value.
>
>
> - Quota: Like metric descriptors, quota descriptors end up listing the
> set of facts used for each quota of the given type, which determines the
> dimensions of the underlying value.
>
>
> The mixer takes the input from the caller, looks up the associated
> descriptors to know the require set of facts. The mixer then composes
> together a struct that contains the parameters from the caller along with
> the resolved facts and hands this to the adapters.
>
> So there's a clean separation between what the code knows and what the
> config specifies. Only the code knows which metric value to update, which
> quota value to update at a given point in time.


I think this is an extension of the discussion about the distinction
between facts and metrics/amounts etc.
I agree that only the client knows when to update 'count of http requests',
I think the question here is whether it needs to know *why* it's doing that.
For example the 'count of http requests in unit of time' could be used to
inform two different quotas, e.g. 5min rate limit and daily limit. Should
the client name both of these in a QuotaRequest?

**Comment by geeknoid** [comment]
Good question.

In the Chemist world, we have metrics as one concept and then limits as
another. You can apply N limits to a given metric. So the code just
understands "# HTTP Request" and the implementation can impose multiple
limits on that single counter. The problem with the Chemist model however
is that even though we pretend the metrics are the same as normal metrics,
they're in fact very special. They need to be of a special kind and type
and they are implicitly updated by quota allocation & free calls. I decided
to break the relationship between these two things at the API level to
avoid this kind of close coupling. In the process I lost the ability to
have multiple limits for a single counter.

I think this can easily be remedied in the configuration space by moving
the limit configuration to a sub-message and use a repeated field within
the QuotaRequest. So for a single counter, you can now have multiple
orthogonal limits, potentially using different sets of facts. Pretty cool
actually.

**Comment by louiscryan** [comment]
On Tue, Dec 6, 2016 at 12:23 PM, Martin Taillefer <notifications@github.com>
wrote:

> Good question.
>
> In the Chemist world, we have metrics as one concept and then limits as
> another. You can apply N limits to a given metric. So the code just
> understands "# HTTP Request" and the implementation can impose multiple
> limits on that single counter. The problem with the Chemist model however
> is that even though we pretend the metrics are the same as normal metrics,
> they're in fact very special.


Can we explore this a little. I agree that a single counter is likely to be
insufficient but perhaps something more refined can still be considered a
fact? i.e metrics are just a special type of fact logically


> They need to be of a special kind and type
> and they are implicitly updated by quota allocation & free calls.


The free use-case is certainly interesting; does the client need to know
that a quota was consumed to do the free? Is there any utility in such an
optimization or is it sufficient for a client to state resources consumed
and released without any knowledge of whether a quota was applied to those
resources or not.


> I decided
> to break the relationship between these two things at the API level to
> avoid this kind of close coupling.


This might indeed be the right approach, just trying to get a feel for the
type of coupling


> In the process I lost the ability to
> have multiple limits for a single counter.
>
> I think this can easily be remedied in the configuration space by moving
> the limit configuration to a sub-message and use a repeated field within
> the QuotaRequest. So for a single counter, you can now have multiple
> orthogonal limits, potentially using different sets of facts. Pretty cool
> actually.
>

Yup, I think this is a property we definitely want/need.

**Comment by wora** [comment]
Regarding 3 interfaces, one gRPC endpoint can serve any number of interfaces. The 3 functions (check, report, quota) don't seem to have much overlap, so it is fine to treat them as separate interfaces. Not a strong point.

For metrics, typically clients need to do aggregation, at least for high traffic services like bigtable, memcache. We probably need a way to configure the aggregation. I don't think a single default works for everyone.

**Comment by geeknoid** [comment]
API is in. Please open other issues for emerging discussions.
