### ISSUE TITLE
Support a way for a list checker to add attributes

### ISSUE THREAD

**Issue by gbrail** [istio/mixer#718]
We will likely have a number of adapters that work by checking something on the request. But the result is not just a boolean -- if they return "success" they also produce additional metadata that should be used by subsequent adapters. 

For instance, a list checker for authentication might return "true" and also set metadata about the application or user that was authenticated, such as the supported quota for that user or application. The value of the quota would then be passed to the quota adapter as a parameter instead of a hard-coded value.

In order to support this scenario, I think that we need a way for an adapter to return attributes. I could see two ways to do this:

1) Just let the adapter set attributes, that can be attached directly to the request so that additional adapters can discover them using their normal processing. In other words, an adapter could set an HTTP header by setting a value in the request.headers attribute.
2) Let the adapter return a set of attributes in its own namespace, and use additional configuration to map those attributes to actual request attributes. In other words, the adapter might return an attribute named "authenticated-user-id," and we would use Istio configuration to map that value to something in request.headers.

One way to do this now without changing the Mixer is to create an "Attributes" adapter that sets attributes to the result of the authentication, and then use a separate "check" or even "deny" adapter to reject the request based on an "authentication.succeeded" attribute or something like that.

Otherwise, what we really want is something that works just like an "attributes" adapter but lets the adapter reject the "check" request as well.

**Comment by rlguarino** [comment]
Is there any update on this? I remember talking to @ZackButcher a few weeks ago and I think he said that it's already possible to do this in an Adapter, but the Envoy filter didn't properly support it. Is there a ticket for that work specifically?

**Comment by ZackButcher** [comment]
These are slightly different usecases: Greg was asking for (what we now call) `attributes` adapter features, that is, being able to introduce new attributes into Mixer's request context for use by other adapters inside of Mixer. We support this today, and its how we introduce k8s metadata into Mixer (e.g. `source.labels` attribute is populated this way).

Ross, IIRC you're looking to be able send attributes from Mixer back to the proxies. This work has not yet been committed to, but it's likely something we'll touch on in our planning for Istio's 0.3 release in the next two weeks.

I am going to keep this issue around/open even though we've addressed Greg's original ask already, because today the system is not extensible: there's a fixed way to implement an attributes adapter, and it's not similar to implementing other adapters. I'd like to see attributes style adapters that're similar to Istio 0.2's other adapters (today `attributes` adapters look a lot like Istio 0.1 adapters).

**Comment by rlguarino** [comment]
I think there was a discussion on the Istio 0.2 design document about attribute generating adapters. I'll link that comment thread to this Issue then. I think the argument was that these types of adapters are not actually that different from current adapters. 

As for the work to get attributes back to the Poxies I'd definitely be interested in using that feature. It would be particularly useful in a Authentication system. Is there any place for that discussion?

**Comment by ZackButcher** [comment]
I thought we had issues filed for it, but I couldn't find them - feel free to file one here. Discussion on it, and other 0.3 issues, should start up in early October, after we get the 0.2 release out the door.

**Comment by rlguarino** [comment]
I've filed https://github.com/istio/mixer/issues/1333 to track this
request. When it comes time to do planning let me know. I'd be willing to
help out here. I'll just need some direction and help with design.

**Comment by gbrail** [comment]
I think that we're making progress with the new Mixer model, so this may
not be a blocker for now.

However, the requirement for a Mixer adapter to be able to customize
aspects of the error that is returned from a "check" failure, such as an
HTTP status code, remains very important and I don't recall if that's in
another issue or in this one.

**Comment by ZackButcher** [comment]
We support returning a [google.rpc.Status](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) from your adapter that gets handed to the proxy, and there's a well established mapping of rpc status Code to HTTP code.

**Comment by geeknoid** [comment]
We're doing this kind of behavior with APAs which are a big focus of the 0.3 work.
